@startuml LDP

class MainWindow {
    'Fields
    - size
    - title
    - loadingScreen : mp4/gif /' watch pdf '/
}

class Cell {
    'Fields
    - <T> cellObject

    'Methods
    - setCellObject(cellObject: T)
    - getCellObject(): T
    - isEmpty(): boolean
    - destroy(): void
}


class Candy {
    'Fields
    - candyId  /' candyId is more understandable'/
    - color : Color
    - isSpecial : True..False

    'Methods
    - getId()
    - getColor()
    - setColor(color)
    - setSpeciality(candySpeciality)
}

class candySpeciality {
    'Fields
    - type
    - value

    'Methods
    - getType()
    - getValue()
    - setValue(value)
}

class Wall {
    'Fields
    - state /' state is better than id '/

    'Methods
    - changeState(newState)
    - setState(newState)
}

/'
Enum > Class?
Will have to watch how we will implement this to decide
'/
enum Color {
    'Fields
    - red
    - orange
    - yellow
    - green
    - blue
    - purple

    'Methods
}

class Board{
    'Fields
    - vertex<Cell>
    - width
    - height
    - lastMoveTime
    - numberOfMovesPlayed

    'Methods
    - getCell(x, y)
    - updateCell(x, y, cellObject)
    - getWidth(): number
    - getHeight(): number
    - updateBoard()
    - isPlayable(): boolean
    - suggestMove()
}

class Icing{
    'Fields
    - type: 0..1..2 /' if 0 delete '/

    'Methods
    - getType(): number
    - setType(type: number)
}

abstract Animation {
    'Fields
    - duration
    - easing /' What's easing? '/
    - callback /' What's callback '/

    'Methods
    - animate()
    /' Removed start and stop because you would need to call
    stop 60 times a second? Right? '/
}

class Slide {}

class Explosion {}

class Score{
    'Fields
    - score
    - highScore

    'Methods
    - getScore(): number
    - calculateScore(Action)
    - updateScore(actionScore : score)
    - checkForNewHighScore(currentScore)
    - getHighScore(): number
    - setHighScore(highScore: number)

}

class StartScreen {
    'Fields
    - highScore
    - choiceButtons : Buttons
}

enum Buttons {
    'Fields
    - play
    - options?
    - exit

}

Explosion-up->Animation
Slide-up->Animation
Board--MainWindow
Score--MainWindow
Cell--Board
Wall--Cell
Candy--Cell
Color-up->Candy
Icing->Candy
candySpeciality->Candy
Animation->Cell
StartScreen--MainWindow
Buttons-right->MainWindow
/' What's the difference between Wall and Icing? '/
@enduml
